# Generated by Django 5.2.5 on 2025-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
