# Generated by Django 5.2.5 on 2025-09-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntruderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='blocked', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unauthorized_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.unauthorizedattempt')),
            ],
        ),
    ]
