# Generated by Django 5.2.5 on 2025-09-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('networks', '0004_delete_unauthorizedattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruderlog',
            name='network',
            field=models.ForeignKey(blank=True, help_text='Network where the intruder attempt occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intruder_logs', to='networks.network'),
        ),
    ]
