# Generated by Django 5.2.5 on 2025-09-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_required', models.BooleanField(default=False)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='companies.company')),
            ],
        ),
    ]
