# Generated by Django 5.2.5 on 2025-09-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_joinrequest_decided_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnauthorizedAttempt',
        ),
    ]
